# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3dbe8c0603344676eb36f57803510b77e21e19c2345b59c06432467f819298919c5e9e134940df805f1e9ca129701d3641f50aef9afe39de38f20ee232cead55

test:
  secret_key_base: 2fd0df27da74a0b9185d0fb171a7568f83075a8a98a74c235bc8698fac68b894162527c18e64db3e9040a21c07344ec57d4da915ef4525b43839f0ca53bff9f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
